spring:
  # redis config
  redis:
    database: 0
#    host: 10.169.6.145
    # 腾讯云
#    host: 110.40.192.18
    host: 192.168.159.3
    port: 6379
#    password: 78ia9555lqQfPMg0qq9ZfoEOTlgtqv03
    jedis:
      timeout: 10000 #连接超时时间
      pool:
        max-active: 8 #最大连接数
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 8 #最大空闲
        min-idle: 0 #最小空闲
  # db config
  datasource:
#    username: chngc_test
    username: root
#    password: VSwiAtXfXf8BAzD1
    password: root123#
#    url: jdbc:mysql://rm-j5eaiyrr2koq1g96b.mysql.rds.aliyuncs.com:3306/test_backup?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    # 腾讯云
    url: jdbc:mysql://110.40.192.18:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml

demo:
  elasticsearch:
#    url: localhost:9200
    # 腾讯云
    url: 110.40.192.18:9200
